on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Artifacts Registry Access
        run: | 
          if [ -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" ]; then
            echo "@zero65:registry=https://asia-south1-npm.pkg.dev/zero65/npm/" > ~/.npmrc
            mkdir -p ~/.config/gcloud
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.config/gcloud/application_default_credentials.json
            npm install -g google-artifactregistry-auth
            npx google-artifactregistry-auth
            cat ~/.config/gcloud/application_default_credentials.json
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/zero65-419011/docker/workflows:latest .

      - name: Push Docker Image
        run: |
          docker push asia-south1-docker.pkg.dev/zero65-419011/docker/workflows:latest
