on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t asia-south1-docker.pkg.dev/zero65-419011/docker/workflows:latest .

      - name: Push Docker Image
        run: |
          docker push asia-south1-docker.pkg.dev/zero65-419011/docker/workflows:latest
